package com.fashion.order.common.enums;

public enum EventType {
    PERMISSION_REGISTER,
    USER_CREATED,
    SHOP_MANAGEMENT_CREATED,
    ORDER_CREATED,
    SAGA_PAYMENT_COMMAND,
    SAGA_PROMOTION_COMMAND,
    SAGA_SHIPPING_COMMAND,
    SAGA_INVENTORY_COMMAND,
    SAGA_PAYMENT_COMPENSATION,
    SAGA_PROMOTION_COMPENSATION,
    SAGA_SHIPPING_COMPENSATION,
    SAGA_INVENTORY_COMPENSATION,
}