package com.fashion.resource.common.enums;

public enum FileEnum {
    USER_AVATAR, 
    PRODUCT_THUMBNAIL,
    PRODUCT_SKU_THUMBNAIL,
    SM_BUSINESS_LICENSE,
    SM_IDENTIFICATION_IMAGE_FIRST,
    SM_IDENTIFICATION_IMAGE_SECOND,
    SM_LOGO,
    SM_THUMBNAIL,
}
